### PR TITLE
Fixed broken tests from #199.

### PR DESCRIPTION
**Pull request by chr15m**
@robertkowalski

### CODE REVIEW

**Comment by chr15m** [comment]
Note: we should remove `test/put-get.js` from this since it is superfluous (already covered by `test/dht_store_mutable.js`).

**Comment by robertkowalski** [comment]
thx! makes sense now.

**Comment by feross** [comment]
Can someone explain the purpose of this PR? That would help me to review it. Thanks.

**Comment by chr15m** [comment]
Hi @ferros - thanks for taking the time to review this patch.

It has been a while but after reviewing I think this patch just adds a test for mutable DHT `put()`, specifically with `salt` defined. Prior to this patch there is only a test for mutable `put()` with no `salt`.

See #190 for details of changes to mutable `put()` with `salt` which are covered by the test in this patch.

**Pull request merged**
