### PR TITLE
Option to ignore locally cached mutable get.

### LINKED ISSUE #194: Option to ignore mutable put value and defer to network value instead
DHT mutable values may be updated out of band and there should be a way for the user to specify they would like to trust the network value rather than their local value.

There is a PR for this already in #155 but I think there is a simpler way to allow the client/user to specify that they want to use a network retrieved value rather than the locally cached value by adding `{nocache: true}` to `opts` when making the DHT `get` request.

Use case for this (as described on #155) is applications where a user has multiple copies of the client running on different devices and all devices are using the same key-pair to write to the same mutable DHT bucket. In that case one of the other copies may update the bucket and we want to make sure we have the latest data rather than our locally cached version.

### PR DESCRIPTION
**Pull request by chr15m**
Fixes #194

### CODE REVIEW

**Comment by feross** [comment]
@mafintosh Any thoughts on this?

**Comment by chr15m** [comment]
@mafintosh I've pushed the changes you requested up.

**Comment by feross** [comment]
Released as 8.3.0

**Comment by feross** [comment]
Edit: I meant 8.4.0

**Pull request merged**
